### ISSUE TITLE
how to install? newbies questions

### ISSUE THREAD

**Issue by zhengniu** [mapbox/tokml#25]
HI Tom,

I download file as zip file, and installed the note.js. But, still have zero clue about the Usage section you mentioned. 

with node, how to install? If you don't mind, could you please provide step by step instructions? 

Really Appreciated

with node/browserify

npm install --save tokml
otherwise:

wget https://raw.github.com/mapbox/tokml/master/tokml.js
as a binary:

npm install -g tokml
tokml file.geojson > file.kml
tokml < file.geojson > file.kml

**Comment by tmcw** [comment]
See https://docs.npmjs.com/getting-started/installing-node & https://docs.npmjs.com/getting-started/installing-npm-packages-globally
