### ISSUE TITLE
Support for MultiLineString?

### ISSUE THREAD

**Issue by billsinc** [mapbox/tokml#29]
I don't seem to be able to convert a MultiLineString geojson object ([http://geojsonlint.com/#sample-MultiLineString](http://geojsonlint.com/#sample-MultiLineString)) to KML.  I assume this is a known limitation?

**Comment by tmcw** [comment]
Hi Bill,

No, [MultiLineString support is implemented](https://github.com/mapbox/tokml/blob/master/index.js#L137) - can you provide an example? Testing the linked example works with tokml on my desktop.

Clarity in terms of providing a concrete example and specifying what the expected output, actual output, and error message, if any, is vital to fixing these issues.
- Tom

**Comment by tmcw** [comment]
Closing; no example, no followup.
