### ISSUE TITLE
CDN js?

### ISSUE THREAD

**Issue by answerquest** [mapbox/tokml#40]
Hi, I want to run this from a google apps script. I can't do it the node way there.. will need to do a traditional  `<script src="path/to/js"></script>` . Any leads? I'm not interested in the additional file generation et al, just being able to convert a geojson string to a kml string would be great!

**Comment by kriscarle** [comment]
@answerquest you can download the built file from https://raw.githubusercontent.com/mapbox/tokml/master/tokml.js and put it somewhere on the web where you can load it from the script tag. It is built with browserify so once it is loaded you should be able to access `tokml()` globally like in the README example.

**Comment by answerquest** [comment]
Thanks! Will try this out in the next cycle.
